import { createContext, useContext, useMemo, useState } from 'react'

export const LANGUAGES = [
  { code: 'es', label: 'Español' },
  { code: 'en', label: 'English' },
  { code: 'pt', label: 'Português' },
]

const translations = {
  es: {
    platform: 'plataforma multiempresa',
    admin: 'Admin',
    business: 'Negocio',
    team: 'Equipo',
    customerRole: 'Cliente',
    signOut: 'Cerrar sesión',
    language: 'Idioma',
    businessPanel: 'Panel de negocios',
    businessPanelDescription: 'Gestiona tu negocio desde Kiosco.',
    chooseOrder: '¿Dónde quieres pedir hoy?',
    chooseOrderDescription: 'Explora un negocio para conocer su catálogo y hacer tu pedido.',
    manageBusiness: 'Administra tu negocio con Kiosco.',
    manageBusinessDescription: 'Gestiona productos, inventario, pedidos, ventas y equipo de trabajo desde la aplicación oficial de Kiosco.',
    android: 'Android',
    iphone: 'iPhone',
    windows: 'Windows',
    loading: 'Cargando…',
    loadingProfile: 'Cargando tu perfil…',
    noConnection: 'Sin conexión',
    connectionDescription: 'Kiosco necesita internet para funcionar. Revisa tu conexión e inténtalo de nuevo.',
    tabs: { dashboard: 'Dashboard', suscripcion: 'Mi suscripción', minegocio: 'Mi negocio', productos: 'Productos', categorias: 'Categorías', inventario: 'Inventario', compras: 'Compras', pedidos: 'Pedidos', ventas: 'Ventas', trabajadores: 'Trabajadores', finanzas: 'Ingresos / Egresos', estadisticas: 'Estadísticas' },
    employeeCode: 'Código para tu empleado',
    copyCode: 'Código copiado — pásaselo a tu empleado',
    newCode: 'Generar uno nuevo',
    generating: 'Generando…',
    authAdmin: { loginTitle: 'Panel de negocios', registerTitle: 'Registra tu negocio en Kiosko', loginDescription: '¿Tu negocio ya está en Kiosko? Ingresa con tu cuenta.', registerDescription: 'Crea tu cuenta — en el siguiente paso configuras (o reclamas) tu negocio.', login: 'Iniciar sesión', register: 'Registrar otro negocio', email: 'Correo', password: 'Contraseña', wait: 'Un momento…', enter: 'Ingresar', createContinue: 'Crear cuenta y continuar', confirmation: 'Te enviamos un correo de confirmación a {email}. Ábrelo, confirma tu cuenta, y vuelve aquí a iniciar sesión.', accountCreated: 'Cuenta creada. Ahora vamos a registrar tu negocio.', back: 'Volver a elegir negocio' },
    authEmployee: { loginTitle: 'Ingresa a atender pedidos', registerTitle: 'Crea tu cuenta de empleado', loginDescription: 'Con tu propio correo — no necesitas el usuario del dueño.', registerDescription: 'Después te pediremos el código de tu negocio.', login: 'Ingresar', create: 'Crear cuenta', wait: 'Un momento…', email: 'Correo', password: 'Contraseña', confirmation: 'Te enviamos un correo de confirmación a {email}. Ábrelo, confirma tu cuenta, y vuelve aquí a iniciar sesión.', accountCreated: 'Cuenta creada. Ahora pon el código que te dio el dueño del negocio.', createQuestion: '¿Todavía no tienes cuenta? Créala aquí', loginQuestion: '¿Ya tienes cuenta? Inicia sesión', codeTitle: 'Código de tu negocio', codeDescription: 'Pídeselo al dueño — son 6 caracteres. Solo lo pones una vez.', codeLabel: 'Código de acceso', verify: 'Verificando…', enterOrders: 'Entrar a atender', linked: 'Listo — ya puedes atender pedidos de {business}', signOut: 'Cerrar sesión' },
    authSuper: { title: 'Acceso de Superadministrador', exclusive: 'Este acceso es exclusivo.', firstSetup: 'Este registro solo funciona una vez, para la primera persona que lo use — si ya existe un superadmin, se rechaza.', email: 'Correo', password: 'Contraseña', wait: 'Un momento…', enter: 'Ingresar', claim: 'Reclamar acceso de superadmin', firstQuestion: '¿Eres tú configurando la plataforma por primera vez?', loginQuestion: '¿Ya tienes cuenta? Inicia sesión', confirmation: 'Te enviamos un correo de confirmación a {email}. Confírmalo y vuelve aquí a iniciar sesión — ahí sí quedará como superadmin.' },
    businessSetup: { chooseTitle: '¿Uno de estos es tu negocio?', chooseDescription: 'Estos negocios ya están en Kiosco pero todavía no tienen administrador. Si alguno es tuyo, reclámalo — quedará vinculado a tu cuenta.', claim: 'Es mío', claiming: 'Reclamando…', newBusiness: 'Ninguno de estos — mi negocio es nuevo', claimed: 'Listo — ya administras {business}', title: 'Cuéntanos de tu negocio', description: 'Esto solo se hace una vez. Después entras directo a tu panel.', name: 'Nombre del negocio', type: '¿A qué se dedica?', descriptionLabel: 'Cuéntanos qué hace tu negocio', slogan: 'Eslogan (opcional)', icon: 'Emoji / ícono', create: 'Registrar mi negocio', creating: 'Creando…', back: 'Volver a la lista de negocios', defaultSlogan: 'Recién llegado a Kiosko', businessCreated: '{business} quedó registrado — ya puedes administrarlo', signOut: 'Cerrar sesión' },
    access: { deniedTitle: 'No tienes acceso a esta sección', signOut: 'Cerrar sesión' },
    report: { title: 'Reporte por día o mes', description: 'Para llevar al banco o para tu control — imprime o guarda como PDF.', byDay: 'Por día', byMonth: 'Por mes', print: 'Imprimir / PDF', period: 'Periodo', otherIncome: 'Otros ingresos', staffPayments: 'Pagos personal', result: 'Resultado del periodo', noMovements: 'No hay movimientos registrados en este periodo.' },
    staff: { title: 'Trabajadores', description: 'Equipo de {business}.', new: 'Nuevo trabajador', active: 'Activo', paused: 'Pausado', editSalary: 'Editar salario', registerPayment: 'Registrar pago', deactivate: 'Desactivar', activate: 'Activar', lastPayment: 'Último pago', added: 'Trabajador agregado', salaryUpdated: 'Salario actualizado', paymentRegistered: 'Pago registrado a {name}', edit: 'Editar a {name}', name: 'Nombre', role: 'Cargo', monthlyPay: 'Pago mensual (COP)', add: 'Agregar trabajador', payTitle: 'Registrar pago', period: 'Periodo', value: 'Valor (COP)', confirmPayment: 'Confirmar pago' },
    stats: { title: 'Estadísticas', description: 'Lo que más se mueve en {business}.', bestSellers: 'Productos más vendidos', noSales: 'Aún no hay ventas para graficar.', overview: 'Panorama general', activeProducts: 'Productos activos', soldOutProducts: 'Productos agotados', lowStockIngredients: 'Ingredientes con bajo stock', activeStaff: 'Trabajadores activos', totalOrders: 'Pedidos totales', totalSales: 'Total histórico vendido' },
    orderShared: { additions: 'Adiciones', quantity: 'Cantidad', notes: 'Observaciones', notesPlaceholder: 'Ej: sin cebolla', addToCart: 'Agregar al carrito', editTitle: 'Editar pedido', editDescription: 'Ajusta cantidades, quita productos o agrega otros. El total se recalcula solo.', empty: 'Sin productos — agrega al menos uno para poder guardar.', addProduct: 'Agregar producto', chooseProduct: 'Elige un producto', saving: 'Guardando…', save: 'Guardar cambios', cancelTitle: '¿Cancelar este pedido?', cancelDescription: 'Esta acción no se puede deshacer, pero el pedido se conserva en el historial marcado como «Cancelado».', back: 'Volver', cancelling: 'Cancelando…' },
    catalogAdmin: { product: 'Producto', products: 'Productos', newProduct: 'Nuevo producto', editProduct: 'Editar producto', createProduct: 'Crear producto', additional: 'Adicional', additionals: 'Adicionales', newAdditional: 'Nuevo adicional', editAdditional: 'Editar adicional', createAdditional: 'Crear adicional', catalogDescription: 'Catálogo configurable de {business} — {count} productos.', additionsDescription: 'Extras que el cliente puede agregar a cualquier producto.', noAdditions: 'Aún no has creado adicionales.', active: 'Activo', inactive: 'Inactivo', availableAgain: 'disponible de nuevo', markedOut: 'marcado como agotado', activated: 'activado', deactivated: 'desactivado', deleted: 'Producto eliminado', additionalDeleted: 'Adicional eliminado', created: 'Producto creado', updated: 'Producto actualizado', outOfStock: 'Agotado', noStock: 'Sin stock', remaining: 'Quedan {count}', reactivate: 'Reactivar', markOut: 'Marcar agotado', edit: 'Editar', remove: 'Eliminar', photo: 'Foto del producto (opcional)', changePhoto: 'Cambiar foto', uploadPhoto: 'Subir foto', category: 'Categoría', price: 'Precio (COP)', description: 'Descripción', icon: 'Emoji / ícono (se usa si no hay foto)', stock: 'Stock (cantidad disponible — déjalo vacío para no controlar cantidad)', unlimited: 'Sin límite', saving: 'Guardando…', uploading: 'Subiendo foto…', addPrice: 'Precio adicional (COP)' },
    inventory: { categories: 'Categorías', categoriesDescription: 'Organiza el catálogo de {business}.', newCategory: 'Nueva categoría', categoryPlaceholder: 'Ej: Postres', add: 'Agregar', categoryAdded: 'Categoría agregada', cannotDelete: 'No se puede eliminar: hay productos en esta categoría', inventory: 'Inventario', inventoryDescription: 'Existencias de ingredientes y materias primas.', newIngredient: 'Nuevo ingrediente', ingredient: 'Ingrediente', supplies: 'Existencias', minimum: 'Mínimo', status: 'Estado', low: 'Bajo', adjust: 'Ajustar', ingredientAdded: 'Ingrediente agregado', stockUpdated: 'Existencias actualizadas', newIngredientTitle: 'Nuevo ingrediente', unit: 'Unidad de medida', initialStock: 'Existencias iniciales', minimumAlert: 'Nivel mínimo (alerta de reposición)', saveIngredient: 'Guardar ingrediente', adjustStock: 'Ajustar existencias', newAmount: 'Nueva cantidad', save: 'Guardar' },
    finance: { purchases: 'Compras', purchasesDescription: 'Cada compra aumenta el inventario y se registra como egreso.', registerPurchase: 'Registrar compra', noPurchases: 'Todavía no hay compras registradas.', date: 'Fecha', ingredient: 'Ingrediente', quantity: 'Cantidad', value: 'Valor', purchaseRegistered: 'Compra registrada — inventario actualizado', purchaseTitle: 'Registrar compra', purchaseDescription: 'Aumenta el inventario y se contabiliza como egreso.', currentStock: 'Existencia actual', purchasedQuantity: 'Cantidad comprada', totalPaid: 'Valor total pagado (COP)', register: 'Registrar compra', finances: 'Ingresos y egresos', financesDescription: 'Compras, pagos y ventas se reflejan aquí automáticamente.', initialCapital: 'Base inicial', income: 'Ingreso', expense: 'Egreso', currentBalance: 'Saldo actual del negocio', thisMonth: 'Este mes', salesAndOther: 'Ingresos (ventas + otros)', purchaseExpenses: 'Egresos (compras)', staffExpenses: 'Egresos (personal)', otherExpenses: 'Otros egresos', extraIncome: 'Ingresos extra registrados', noManualIncome: 'Sin ingresos manuales aún.', otherCosts: 'Otros gastos', noOtherCosts: 'Sin otros gastos aún.', initialSaved: 'Base inicial guardada', movementSaved: 'Movimiento registrado', initialTitle: 'Base inicial del negocio', saveInitial: 'Guardar base inicial', newIncome: 'Nuevo ingreso', newExpense: 'Nuevo egreso', concept: 'Concepto', save: 'Guardar' },
    customer: { otherBusinesses: 'Ver otros negocios', add: 'Agregar →', outOfStock: 'Agotado', noProducts: 'No hay productos en esta categoría.', viewOrder: 'Ver pedido', order: 'Tu pedido', emptyCart: 'Tu carrito está vacío.', remove: 'Quitar', name: 'Tu nombre', namePlaceholder: '¿Cómo te llamas?', confirm: 'Confirmar pedido', confirming: 'Confirmando…', cancelled: 'Pedido cancelado', confirmed: '¡Pedido confirmado!', cancelledDescription: 'Este pedido fue cancelado y no se va a preparar.', trackingDescription: 'El estado se actualiza solo cuando la cocina lo cambie — no necesitas recargar la página.', edit: 'Editar pedido', cancel: 'Cancelar pedido', newOrder: 'Hacer otro pedido' },
  },
  en: {
    platform: 'multi-business platform',
    admin: 'Admin',
    business: 'Business',
    team: 'Team',
    customerRole: 'Customer',
    signOut: 'Sign out',
    language: 'Language',
    businessPanel: 'Business dashboard',
    businessPanelDescription: 'Manage your business with Kiosco.',
    chooseOrder: 'Where would you like to order today?',
    chooseOrderDescription: 'Explore a business to view its catalog and place your order.',
    manageBusiness: 'Manage your business with Kiosco.',
    manageBusinessDescription: 'Manage products, inventory, orders, sales, and your team from the official Kiosco app.',
    android: 'Android',
    iphone: 'iPhone',
    windows: 'Windows',
    loading: 'Loading…',
    loadingProfile: 'Loading your profile…',
    noConnection: 'No connection',
    connectionDescription: 'Kiosco needs an internet connection. Check your connection and try again.',
    tabs: { dashboard: 'Dashboard', suscripcion: 'My subscription', minegocio: 'My business', productos: 'Products', categorias: 'Categories', inventario: 'Inventory', compras: 'Purchases', pedidos: 'Orders', ventas: 'Sales', trabajadores: 'Staff', finanzas: 'Income / Expenses', estadisticas: 'Statistics' },
    employeeCode: 'Code for your employee',
    copyCode: 'Code copied — share it with your employee',
    newCode: 'Generate a new one',
    generating: 'Generating…',
    authAdmin: { loginTitle: 'Business dashboard', registerTitle: 'Register your business on Kiosco', loginDescription: 'Is your business already on Kiosco? Sign in with your account.', registerDescription: 'Create your account — next you will configure or claim your business.', login: 'Sign in', register: 'Register another business', email: 'Email', password: 'Password', wait: 'One moment…', enter: 'Sign in', createContinue: 'Create account and continue', confirmation: 'We sent a confirmation email to {email}. Open it, confirm your account, and then sign in again.', accountCreated: 'Account created. Now let’s register your business.', back: 'Back to choose a business' },
    authEmployee: { loginTitle: 'Sign in to manage orders', registerTitle: 'Create your staff account', loginDescription: 'Use your own email — you do not need the owner’s account.', registerDescription: 'Next we will ask for your business code.', login: 'Sign in', create: 'Create account', wait: 'One moment…', email: 'Email', password: 'Password', confirmation: 'We sent a confirmation email to {email}. Open it, confirm your account, and then sign in again.', accountCreated: 'Account created. Now enter the code provided by the business owner.', createQuestion: 'Do not have an account yet? Create one here', loginQuestion: 'Already have an account? Sign in', codeTitle: 'Your business code', codeDescription: 'Ask the owner for it — it has 6 characters and is only entered once.', codeLabel: 'Access code', verify: 'Verifying…', enterOrders: 'Start managing orders', linked: 'Done — you can now manage orders for {business}', signOut: 'Sign out' },
    authSuper: { title: 'Superadmin access', exclusive: 'This access is restricted.', firstSetup: 'This registration works only once for the first person who uses it — if a superadmin already exists, it will be rejected.', email: 'Email', password: 'Password', wait: 'One moment…', enter: 'Sign in', claim: 'Claim superadmin access', firstQuestion: 'Are you setting up the platform for the first time?', loginQuestion: 'Already have an account? Sign in', confirmation: 'We sent a confirmation email to {email}. Confirm it and sign in again to become superadmin.' },
    businessSetup: { chooseTitle: 'Is one of these your business?', chooseDescription: 'These businesses are already on Kiosco but do not have an administrator yet. Claim yours to link it to your account.', claim: 'Claim it', claiming: 'Claiming…', newBusiness: 'None of these — my business is new', claimed: 'Done — you now manage {business}', title: 'Tell us about your business', description: 'This is only needed once. Then you will go straight to your dashboard.', name: 'Business name', type: 'What does it do?', descriptionLabel: 'Tell us what your business does', slogan: 'Slogan (optional)', icon: 'Emoji / icon', create: 'Register my business', creating: 'Creating…', back: 'Back to business list', defaultSlogan: 'New to Kiosco', businessCreated: '{business} is registered — you can now manage it', signOut: 'Sign out' },
    access: { deniedTitle: 'You do not have access to this section', signOut: 'Sign out' },
    report: { title: 'Daily or monthly report', description: 'For the bank or your records — print or save as PDF.', byDay: 'By day', byMonth: 'By month', print: 'Print / PDF', period: 'Period', otherIncome: 'Other income', staffPayments: 'Staff payments', result: 'Period result', noMovements: 'No transactions recorded for this period.' },
    staff: { title: 'Staff', description: '{business} team.', new: 'New staff member', active: 'Active', paused: 'Paused', editSalary: 'Edit pay', registerPayment: 'Record payment', deactivate: 'Deactivate', activate: 'Activate', lastPayment: 'Last payment', added: 'Staff member added', salaryUpdated: 'Pay updated', paymentRegistered: 'Payment recorded for {name}', edit: 'Edit {name}', name: 'Name', role: 'Role', monthlyPay: 'Monthly pay (COP)', add: 'Add staff member', payTitle: 'Record payment', period: 'Period', value: 'Amount (COP)', confirmPayment: 'Confirm payment' },
    stats: { title: 'Statistics', description: 'What is moving most in {business}.', bestSellers: 'Best-selling products', noSales: 'There are no sales to chart yet.', overview: 'Overview', activeProducts: 'Active products', soldOutProducts: 'Sold-out products', lowStockIngredients: 'Low-stock ingredients', activeStaff: 'Active staff', totalOrders: 'Total orders', totalSales: 'Total historical sales' },
    orderShared: { additions: 'Add-ons', quantity: 'Quantity', notes: 'Notes', notesPlaceholder: 'E.g. no onions', addToCart: 'Add to cart', editTitle: 'Edit order', editDescription: 'Adjust quantities, remove items, or add others. The total recalculates automatically.', empty: 'No products — add at least one before saving.', addProduct: 'Add product', chooseProduct: 'Choose a product', saving: 'Saving…', save: 'Save changes', cancelTitle: 'Cancel this order?', cancelDescription: 'This cannot be undone, but the order will remain in history marked as «Cancelled».', back: 'Back', cancelling: 'Cancelling…' },
    catalogAdmin: { product: 'Product', products: 'Products', newProduct: 'New product', editProduct: 'Edit product', createProduct: 'Create product', additional: 'Add-on', additionals: 'Add-ons', newAdditional: 'New add-on', editAdditional: 'Edit add-on', createAdditional: 'Create add-on', catalogDescription: 'Configurable catalog for {business} — {count} products.', additionsDescription: 'Extras customers can add to any product.', noAdditions: 'You have not created any add-ons yet.', active: 'Active', inactive: 'Inactive', availableAgain: 'available again', markedOut: 'marked as sold out', activated: 'activated', deactivated: 'deactivated', deleted: 'Product deleted', additionalDeleted: 'Add-on deleted', created: 'Product created', updated: 'Product updated', outOfStock: 'Sold out', noStock: 'Out of stock', remaining: '{count} remaining', reactivate: 'Reactivate', markOut: 'Mark sold out', edit: 'Edit', remove: 'Delete', photo: 'Product photo (optional)', changePhoto: 'Change photo', uploadPhoto: 'Upload photo', category: 'Category', price: 'Price (COP)', description: 'Description', icon: 'Emoji / icon (used when there is no photo)', stock: 'Stock (available quantity — leave empty for unlimited)', unlimited: 'Unlimited', saving: 'Saving…', uploading: 'Uploading photo…', addPrice: 'Add-on price (COP)' },
    inventory: { categories: 'Categories', categoriesDescription: 'Organize the catalog for {business}.', newCategory: 'New category', categoryPlaceholder: 'E.g. Desserts', add: 'Add', categoryAdded: 'Category added', cannotDelete: 'Cannot delete: this category has products', inventory: 'Inventory', inventoryDescription: 'Ingredients and raw materials in stock.', newIngredient: 'New ingredient', ingredient: 'Ingredient', supplies: 'Stock', minimum: 'Minimum', status: 'Status', low: 'Low', adjust: 'Adjust', ingredientAdded: 'Ingredient added', stockUpdated: 'Stock updated', newIngredientTitle: 'New ingredient', unit: 'Unit of measure', initialStock: 'Initial stock', minimumAlert: 'Minimum level (restock alert)', saveIngredient: 'Save ingredient', adjustStock: 'Adjust stock', newAmount: 'New quantity', save: 'Save' },
    finance: { purchases: 'Purchases', purchasesDescription: 'Each purchase increases inventory and is recorded as an expense.', registerPurchase: 'Register purchase', noPurchases: 'No purchases registered yet.', date: 'Date', ingredient: 'Ingredient', quantity: 'Quantity', value: 'Value', purchaseRegistered: 'Purchase registered — inventory updated', purchaseTitle: 'Register purchase', purchaseDescription: 'Increase inventory and record the cost as an expense.', currentStock: 'Current stock', purchasedQuantity: 'Quantity purchased', totalPaid: 'Total paid (COP)', register: 'Register purchase', finances: 'Income and expenses', financesDescription: 'Purchases, payments, and sales appear here automatically.', initialCapital: 'Opening balance', income: 'Income', expense: 'Expense', currentBalance: 'Current business balance', thisMonth: 'This month', salesAndOther: 'Income (sales + other)', purchaseExpenses: 'Expenses (purchases)', staffExpenses: 'Expenses (staff)', otherExpenses: 'Other expenses', extraIncome: 'Additional income', noManualIncome: 'No manual income yet.', otherCosts: 'Other costs', noOtherCosts: 'No other costs yet.', initialSaved: 'Opening balance saved', movementSaved: 'Transaction registered', initialTitle: 'Business opening balance', saveInitial: 'Save opening balance', newIncome: 'New income', newExpense: 'New expense', concept: 'Description', save: 'Save' },
    customer: { otherBusinesses: 'View other businesses', add: 'Add →', outOfStock: 'Sold out', noProducts: 'There are no products in this category.', viewOrder: 'View order', order: 'Your order', emptyCart: 'Your cart is empty.', remove: 'Remove', name: 'Your name', namePlaceholder: 'What is your name?', confirm: 'Place order', confirming: 'Confirming…', cancelled: 'Order cancelled', confirmed: 'Order confirmed!', cancelledDescription: 'This order was cancelled and will not be prepared.', trackingDescription: 'The status updates when the kitchen changes it — no refresh needed.', edit: 'Edit order', cancel: 'Cancel order', newOrder: 'Place another order' },
  },
  pt: {
    platform: 'plataforma multinegócios',
    admin: 'Admin',
    business: 'Negócio',
    team: 'Equipe',
    customerRole: 'Cliente',
    signOut: 'Sair',
    language: 'Idioma',
    businessPanel: 'Painel de negócios',
    businessPanelDescription: 'Gerencie seu negócio com o Kiosco.',
    chooseOrder: 'Onde você quer pedir hoje?',
    chooseOrderDescription: 'Explore um negócio, veja o catálogo e faça seu pedido.',
    manageBusiness: 'Gerencie seu negócio com o Kiosco.',
    manageBusinessDescription: 'Gerencie produtos, estoque, pedidos, vendas e equipe pelo aplicativo oficial do Kiosco.',
    android: 'Android',
    iphone: 'iPhone',
    windows: 'Windows',
    loading: 'Carregando…',
    loadingProfile: 'Carregando seu perfil…',
    noConnection: 'Sem conexão',
    connectionDescription: 'O Kiosco precisa de internet para funcionar. Verifique sua conexão e tente novamente.',
    tabs: { dashboard: 'Painel', suscripcion: 'Minha assinatura', minegocio: 'Meu negócio', productos: 'Produtos', categorias: 'Categorias', inventario: 'Estoque', compras: 'Compras', pedidos: 'Pedidos', ventas: 'Vendas', trabajadores: 'Equipe', finanzas: 'Entradas / Saídas', estadisticas: 'Estatísticas' },
    employeeCode: 'Código para seu funcionário',
    copyCode: 'Código copiado — compartilhe com seu funcionário',
    newCode: 'Gerar um novo',
    generating: 'Gerando…',
    authAdmin: { loginTitle: 'Painel de negócios', registerTitle: 'Cadastre seu negócio no Kiosco', loginDescription: 'Seu negócio já está no Kiosco? Entre com sua conta.', registerDescription: 'Crie sua conta — depois você configurará ou reivindicará seu negócio.', login: 'Entrar', register: 'Cadastrar outro negócio', email: 'E-mail', password: 'Senha', wait: 'Aguarde…', enter: 'Entrar', createContinue: 'Criar conta e continuar', confirmation: 'Enviamos um e-mail de confirmação para {email}. Abra, confirme sua conta e entre novamente.', accountCreated: 'Conta criada. Agora vamos cadastrar seu negócio.', back: 'Voltar para escolher negócio' },
    authEmployee: { loginTitle: 'Entre para atender pedidos', registerTitle: 'Crie sua conta de funcionário', loginDescription: 'Use seu próprio e-mail — você não precisa da conta do proprietário.', registerDescription: 'Depois pediremos o código do seu negócio.', login: 'Entrar', create: 'Criar conta', wait: 'Aguarde…', email: 'E-mail', password: 'Senha', confirmation: 'Enviamos um e-mail de confirmação para {email}. Abra, confirme sua conta e entre novamente.', accountCreated: 'Conta criada. Agora informe o código fornecido pelo proprietário.', createQuestion: 'Ainda não tem uma conta? Crie aqui', loginQuestion: 'Já tem uma conta? Entre', codeTitle: 'Código do seu negócio', codeDescription: 'Peça ao proprietário — são 6 caracteres e você só informa uma vez.', codeLabel: 'Código de acesso', verify: 'Verificando…', enterOrders: 'Entrar para atender', linked: 'Pronto — agora você pode atender pedidos de {business}', signOut: 'Sair' },
    authSuper: { title: 'Acesso de superadministrador', exclusive: 'Este acesso é exclusivo.', firstSetup: 'Este cadastro funciona apenas uma vez, para a primeira pessoa que o usar — se já existir um superadmin, será recusado.', email: 'E-mail', password: 'Senha', wait: 'Aguarde…', enter: 'Entrar', claim: 'Reivindicar acesso de superadmin', firstQuestion: 'Você está configurando a plataforma pela primeira vez?', loginQuestion: 'Já tem uma conta? Entre', confirmation: 'Enviamos um e-mail de confirmação para {email}. Confirme e entre novamente para ser superadmin.' },
    businessSetup: { chooseTitle: 'Algum destes é seu negócio?', chooseDescription: 'Estes negócios já estão no Kiosco, mas ainda não têm administrador. Reivindique o seu para vinculá-lo à sua conta.', claim: 'É meu', claiming: 'Reivindicando…', newBusiness: 'Nenhum destes — meu negócio é novo', claimed: 'Pronto — agora você administra {business}', title: 'Conte-nos sobre seu negócio', description: 'Isso só é feito uma vez. Depois você entra direto no painel.', name: 'Nome do negócio', type: 'Qual é a atividade?', descriptionLabel: 'Conte-nos o que seu negócio faz', slogan: 'Slogan (opcional)', icon: 'Emoji / ícone', create: 'Cadastrar meu negócio', creating: 'Criando…', back: 'Voltar para a lista de negócios', defaultSlogan: 'Novo no Kiosco', businessCreated: '{business} foi cadastrado — você já pode administrá-lo', signOut: 'Sair' },
    access: { deniedTitle: 'Você não tem acesso a esta seção', signOut: 'Sair' },
    report: { title: 'Relatório por dia ou mês', description: 'Para levar ao banco ou para seu controle — imprima ou salve como PDF.', byDay: 'Por dia', byMonth: 'Por mês', print: 'Imprimir / PDF', period: 'Período', otherIncome: 'Outras entradas', staffPayments: 'Pagamentos da equipe', result: 'Resultado do período', noMovements: 'Não há movimentos registrados neste período.' },
    staff: { title: 'Equipe', description: 'Equipe de {business}.', new: 'Novo funcionário', active: 'Ativo', paused: 'Pausado', editSalary: 'Editar salário', registerPayment: 'Registrar pagamento', deactivate: 'Desativar', activate: 'Ativar', lastPayment: 'Último pagamento', added: 'Funcionário adicionado', salaryUpdated: 'Salário atualizado', paymentRegistered: 'Pagamento registrado para {name}', edit: 'Editar {name}', name: 'Nome', role: 'Cargo', monthlyPay: 'Pagamento mensal (COP)', add: 'Adicionar funcionário', payTitle: 'Registrar pagamento', period: 'Período', value: 'Valor (COP)', confirmPayment: 'Confirmar pagamento' },
    stats: { title: 'Estatísticas', description: 'O que mais se movimenta em {business}.', bestSellers: 'Produtos mais vendidos', noSales: 'Ainda não há vendas para gerar o gráfico.', overview: 'Visão geral', activeProducts: 'Produtos ativos', soldOutProducts: 'Produtos esgotados', lowStockIngredients: 'Ingredientes com estoque baixo', activeStaff: 'Funcionários ativos', totalOrders: 'Total de pedidos', totalSales: 'Total histórico vendido' },
    orderShared: { additions: 'Adicionais', quantity: 'Quantidade', notes: 'Observações', notesPlaceholder: 'Ex.: sem cebola', addToCart: 'Adicionar ao carrinho', editTitle: 'Editar pedido', editDescription: 'Ajuste quantidades, remova produtos ou adicione outros. O total é recalculado automaticamente.', empty: 'Sem produtos — adicione pelo menos um antes de salvar.', addProduct: 'Adicionar produto', chooseProduct: 'Escolha um produto', saving: 'Salvando…', save: 'Salvar alterações', cancelTitle: 'Cancelar este pedido?', cancelDescription: 'Esta ação não pode ser desfeita, mas o pedido continuará no histórico marcado como «Cancelado».', back: 'Voltar', cancelling: 'Cancelando…' },
    catalogAdmin: { product: 'Produto', products: 'Produtos', newProduct: 'Novo produto', editProduct: 'Editar produto', createProduct: 'Criar produto', additional: 'Adicional', additionals: 'Adicionais', newAdditional: 'Novo adicional', editAdditional: 'Editar adicional', createAdditional: 'Criar adicional', catalogDescription: 'Catálogo configurável de {business} — {count} produtos.', additionsDescription: 'Extras que o cliente pode adicionar a qualquer produto.', noAdditions: 'Você ainda não criou adicionais.', active: 'Ativo', inactive: 'Inativo', availableAgain: 'disponível novamente', markedOut: 'marcado como esgotado', activated: 'ativado', deactivated: 'desativado', deleted: 'Produto excluído', additionalDeleted: 'Adicional excluído', created: 'Produto criado', updated: 'Produto atualizado', outOfStock: 'Esgotado', noStock: 'Sem estoque', remaining: 'Restam {count}', reactivate: 'Reativar', markOut: 'Marcar como esgotado', edit: 'Editar', remove: 'Excluir', photo: 'Foto do produto (opcional)', changePhoto: 'Alterar foto', uploadPhoto: 'Enviar foto', category: 'Categoria', price: 'Preço (COP)', description: 'Descrição', icon: 'Emoji / ícone (usado quando não há foto)', stock: 'Estoque (quantidade disponível — deixe vazio para ilimitado)', unlimited: 'Sem limite', saving: 'Salvando…', uploading: 'Enviando foto…', addPrice: 'Preço do adicional (COP)' },
    inventory: { categories: 'Categorias', categoriesDescription: 'Organize o catálogo de {business}.', newCategory: 'Nova categoria', categoryPlaceholder: 'Ex.: Sobremesas', add: 'Adicionar', categoryAdded: 'Categoria adicionada', cannotDelete: 'Não é possível excluir: há produtos nesta categoria', inventory: 'Estoque', inventoryDescription: 'Ingredientes e matérias-primas em estoque.', newIngredient: 'Novo ingrediente', ingredient: 'Ingrediente', supplies: 'Existências', minimum: 'Mínimo', status: 'Status', low: 'Baixo', adjust: 'Ajustar', ingredientAdded: 'Ingrediente adicionado', stockUpdated: 'Estoque atualizado', newIngredientTitle: 'Novo ingrediente', unit: 'Unidade de medida', initialStock: 'Estoque inicial', minimumAlert: 'Nível mínimo (alerta de reposição)', saveIngredient: 'Salvar ingrediente', adjustStock: 'Ajustar estoque', newAmount: 'Nova quantidade', save: 'Salvar' },
    finance: { purchases: 'Compras', purchasesDescription: 'Cada compra aumenta o estoque e é registrada como saída.', registerPurchase: 'Registrar compra', noPurchases: 'Ainda não há compras registradas.', date: 'Data', ingredient: 'Ingrediente', quantity: 'Quantidade', value: 'Valor', purchaseRegistered: 'Compra registrada — estoque atualizado', purchaseTitle: 'Registrar compra', purchaseDescription: 'Aumente o estoque e registre o custo como saída.', currentStock: 'Estoque atual', purchasedQuantity: 'Quantidade comprada', totalPaid: 'Valor total pago (COP)', register: 'Registrar compra', finances: 'Entradas e saídas', financesDescription: 'Compras, pagamentos e vendas aparecem aqui automaticamente.', initialCapital: 'Capital inicial', income: 'Entrada', expense: 'Saída', currentBalance: 'Saldo atual do negócio', thisMonth: 'Este mês', salesAndOther: 'Entradas (vendas + outros)', purchaseExpenses: 'Saídas (compras)', staffExpenses: 'Saídas (equipe)', otherExpenses: 'Outras saídas', extraIncome: 'Entradas extras registradas', noManualIncome: 'Ainda não há entradas manuais.', otherCosts: 'Outros gastos', noOtherCosts: 'Ainda não há outros gastos.', initialSaved: 'Capital inicial salvo', movementSaved: 'Movimento registrado', initialTitle: 'Capital inicial do negócio', saveInitial: 'Salvar capital inicial', newIncome: 'Nova entrada', newExpense: 'Nova saída', concept: 'Descrição', save: 'Salvar' },
    customer: { otherBusinesses: 'Ver outros negócios', add: 'Adicionar →', outOfStock: 'Esgotado', noProducts: 'Não há produtos nesta categoria.', viewOrder: 'Ver pedido', order: 'Seu pedido', emptyCart: 'Seu carrinho está vazio.', remove: 'Remover', name: 'Seu nome', namePlaceholder: 'Como você se chama?', confirm: 'Confirmar pedido', confirming: 'Confirmando…', cancelled: 'Pedido cancelado', confirmed: 'Pedido confirmado!', cancelledDescription: 'Este pedido foi cancelado e não será preparado.', trackingDescription: 'O status é atualizado quando a cozinha o altera — não é preciso recarregar a página.', edit: 'Editar pedido', cancel: 'Cancelar pedido', newOrder: 'Fazer outro pedido' },
  },
}

const LanguageContext = createContext(null)

function initialLanguage() {
  const saved = localStorage.getItem('kiosco-language')
  if (saved && translations[saved]) return saved
  const browserLanguage = navigator.language?.slice(0, 2)
  return translations[browserLanguage] ? browserLanguage : 'es'
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(initialLanguage)
  const setLanguage = (nextLanguage) => {
    if (!translations[nextLanguage]) return
    localStorage.setItem('kiosco-language', nextLanguage)
    setLanguageState(nextLanguage)
  }
  const value = useMemo(() => ({ language, setLanguage, t: translations[language] }), [language])
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  return useContext(LanguageContext)
}
